/// This file is generated by Versionator -- DO NOT EDIT.
/// See github.com/elegantchaos/Versionator for more info.
#define BUILD 4
#define CURRENT_PROJECT_VERSION 4
#define COMMIT "70f8f9a"
#define GIT_VERSION "v1.0.0-0-g70f8f9a"
#define GIT_TAG "v1.0.0"