/// This file is generated by Versionator -- DO NOT EDIT.
/// See github.com/elegantchaos/Versionator for more info.
public struct VersionatorVersion {
    static let string = "70f8f9a"
    static let build = 4
    static let commit = ""
    static let git = "70f8f9a"
    static let tag = "70f8f9a"
    static let full = "70f8f9a (4)"
}