// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
//  Created by Sam Deane on 09/06/22.
//  All code (c) 2022 - present day, Elegant Chaos Limited.
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

import Foundation
import Runner

@main struct VersionatorTool {
  static func main() async {
    let all = ProcessInfo.processInfo.arguments
    let args = all.filter({ !$0.starts(with: "--") })
    guard args.count > 2 else {
      let name = URL(fileURLWithPath: args[0]).lastPathComponent
      print(
        """
          Usage: \(name) <path> {<path> ...}
          
          Calculates the "version" of the git repo at <input-path>, 
          and writes one or more generated files to the supplied paths.

          The file extension of each path determines the format. It can
          be one of: .swift, .plist, or .h.
        """)

      exit(1)
    }

    let root = args[1]
    chdir(root)

    let runner = Runner(command: "git")

    // build number is derived from the commit count on the current branch
    let buildNumber: String
    do {
      let result = try runner.run(arguments: ["rev-list", "--count", "HEAD"])
      buildNumber = await String(result.stdout).trimmingCharacters(in: .whitespacesAndNewlines)

    } catch {
      buildNumber = "unknown"
    }

    let gitVersion: String
    do {
      let result = try runner.run(arguments: ["describe", "--long", "--tags", "--always"])
      gitVersion = await String(result.stdout).trimmingCharacters(in: .whitespacesAndNewlines)
    } catch {
      gitVersion = ""
    }

    let items = gitVersion.split(separator: "-")
    let tag = items.first ?? ""
    var version = tag
    if version.first == "v" { version.removeFirst() }
    let commit = items.count == 3 ? items[2] : ""

    for arg in args.dropFirst(2) {
      let url = URL(fileURLWithPath: arg)
      switch url.pathExtension {
      case "h": writeHeader(to: url, version: version, commit: commit, tag: tag, buildNumber: buildNumber, gitVersion: gitVersion)
      case "swift": writeSwift(to: url, version: version, commit: commit, tag: tag, buildNumber: buildNumber, gitVersion: gitVersion)
      case "plist": writePlist(to: url, buildNumber: buildNumber, commit: commit, gitVersion: gitVersion)
      default: print("Unknown file type '\(url.pathExtension)'")
      }
    }
  }

  /// Write out the generated Swift.
  static func writeSwift(to outputURL: URL, version: String.SubSequence, commit: String.SubSequence, tag: String.SubSequence, buildNumber: String, gitVersion: String) {
    let generatedSwift = """
      /// This file is generated by Versionator -- DO NOT EDIT.
      /// See github.com/elegantchaos/Versionator for more info.
      public struct CurrentVersion {
          static let string = "\(version)"
          static let build = \(buildNumber)
          static let commit = "\(commit)"
          static let git = "\(gitVersion)"
          static let tag = "\(tag)"
          static let full = "\(version) (\(buildNumber))"
      }
      """
    let data = generatedSwift.data(using: .utf8)
    try? FileManager.default.createDirectory(at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
    try? data?.write(to: outputURL)
  }

  static func writeHeader(to outputURL: URL, version: String.SubSequence, commit: String.SubSequence, tag: String.SubSequence, buildNumber: String, gitVersion: String) {
    let generatedHeader = """
      /// This file is generated by Versionator -- DO NOT EDIT.
      /// See github.com/elegantchaos/Versionator for more info.
      #define BUILD \(buildNumber)
      #define CURRENT_PROJECT_VERSION \(buildNumber)
      #define COMMIT \(commit)
      #define GIT_VERSION "\(gitVersion)"
      #define GIT_TAG "\(tag)"
      """
    let data = generatedHeader.data(using: .utf8)
    try? FileManager.default.createDirectory(at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
    try? data?.write(to: outputURL)
  }

  /// Write out the generate Plist
  static func writePlist(to infoURL: URL, buildNumber: String, commit: String.SubSequence, gitVersion: String) {
    let info =
      [
        "CFBundleVersion": buildNumber,
        "Commit": commit,
        "CFBundleShortVersionString": gitVersion,
        "CFBundleInfoDictionaryVersion": 6.0,
      ] as NSDictionary

    let infoData = try? PropertyListSerialization.data(fromPropertyList: info, format: .xml, options: 0)
    try? infoData?.write(to: infoURL)
  }
}
